name: Workflow Artifact
on: merge_group
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: 
          echo "Contenu Artifact" > my_app.txt
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          # Artifact name
          name: mon_application
          # A file, directory or wildcard pattern that describes what to upload
          path: my_app.txt/
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.1.1
        with:
          # Artifact name
          name: mon_application
      - run: |
          ls
          cat my_app.txt
